### ISSUE TITLE
Installation error when following the documentation's demo

### ISSUE THREAD

**Issue by RemiLehe** [slaclab/lume-services#62]
Hi,

Thanks a lot for developing and sharing `lume-services`!

When following the instructions [here](https://slaclab.github.io/lume-services/demo/), I got an error at step 6 ("Create development environment"). More specifically, when running:
```
conda env create -f dev-environment.yml
```
I got the following error:
```
Collecting git+https://github.com/jbellister-slac/lume-services.git@prefect_2 (from -r /Users/rlehe/Desktop/test_lume_services/lume-services-model-template/my-lume-services-model/condaenv.f3v01pk8.requirements.txt (line 1))
  Cloning https://github.com/jbellister-slac/lume-services.git (to revision prefect_2) to /private/var/folders/_d/m96lcmy90_b9sc5fmhg3d_br0000gn/T/pip-req-build-cry5n8ys
  Resolved https://github.com/jbellister-slac/lume-services.git to commit 0e0b35f7f4ba4cb8a7a807fa926374af14fe1467
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting git+https://github.com/slaclab/lume-model.git (from -r /Users/rlehe/Desktop/test_lume_services/lume-services-model-template/my-lume-services-model/condaenv.f3v01pk8.requirements.txt (line 2))
  Cloning https://github.com/slaclab/lume-model.git to /private/var/folders/_d/m96lcmy90_b9sc5fmhg3d_br0000gn/T/pip-req-build-y22wzvjf
  Resolved https://github.com/slaclab/lume-model.git to commit 2921e6583a6cfd49285833eb851b361aacf65b4c
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/jbellister-slac/lume-services.git /private/var/folders/_d/m96lcmy90_b9sc5fmhg3d_br0000gn/T/pip-req-build-cry5n8ys
  Running command git checkout -b prefect_2 --track origin/prefect_2
  Switched to a new branch 'prefect_2'
  branch 'prefect_2' set up to track 'origin/prefect_2'.
  Running command git clone --filter=blob:none --quiet https://github.com/slaclab/lume-model.git /private/var/folders/_d/m96lcmy90_b9sc5fmhg3d_br0000gn/T/pip-req-build-y22wzvjf
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /private/var/folders/_d/m96lcmy90_b9sc5fmhg3d_br0000gn/T/pip-req-build-y22wzvjf/versioneer.py:432: SyntaxWarning: invalid escape sequence '\s'
        ] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/_d/m96lcmy90_b9sc5fmhg3d_br0000gn/T/pip-req-build-y22wzvjf/setup.py", line 23, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/_d/m96lcmy90_b9sc5fmhg3d_br0000gn/T/pip-req-build-y22wzvjf/versioneer.py", line 1524, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/_d/m96lcmy90_b9sc5fmhg3d_br0000gn/T/pip-req-build-y22wzvjf/versioneer.py", line 1451, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/_d/m96lcmy90_b9sc5fmhg3d_br0000gn/T/pip-req-build-y22wzvjf/versioneer.py", line 346, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
```

This seems related to the following line in `lume-model`: 
https://github.com/slaclab/lume-model/blob/master/versioneer.py#L346
~~However, I am able to install `lume-model` by itself (with `pip install git+https://github.com/slaclab/lume-model`) without any issue.~~
Apologies: after double checking, `pip install git+https://github.com/slaclab/lume-model` also fails. I will report this on the `lume-model` repo: https://github.com/slaclab/lume-model/issues/92

Do you know what might be causing this issue?

**Comment by RemiLehe** [comment]
I was able to solve this issue by using Python 3.11 instead of Python 3.12.
